from setuptools import setup, find_namespace_packages

install_requires = ["kafkit[aiohttp]", "aiokafka", "confluent_kafka"]
tests_require = ["pytest", "pytest-cov", "pytest-flake8", "asynctest",
                 "kafkit[aiohttp]", "aiokafka", "confluent_kafka"]
dev_requires = install_requires + tests_require + ["documenteer[pipelines]"]
scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setup(
    name="ts_salkafka",
    description="Forward DDS samples from one or more SAL components to a "
                "Kafka broker, to populate databases..",
    use_scm_version={"write_to": "python/lsst/ts/salkafka/version.py",
                     "write_to_template": scm_version_template},
    setup_requires=["setuptools_scm", "pytest-runner"],
    install_requires=install_requires,
    package_dir={"": "python"},
    packages=find_namespace_packages(where="python"),
    package_data={"": ["*.rst", "*.yaml"]},
    scripts=["bin/run_salkafka_producer.py"],
    tests_require=tests_require,
    extras_require={"dev": dev_requires},
    license="GPL",
    project_urls={
        "Bug Tracker": "https://jira.lsstcorp.org/secure/Dashboard.jspa",
        "Source Code": "https://github.com/lsst-ts/ts_salkafka",
    }
)
