{% set data= load_setup_py_data() %}
package:
  name: ts-salkafka
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/lsst-ts/ts_salkafka
  git_rev: {{ TS_SALKAFKA_VERSION }}

build:
  script: python -m pip install --ignore-installed .
  skip: True #[win]

test:
  requires:
    - pytest
    - pytest-flake8
    - pytest-cov
    - asynctest
    - black == 19.10b0

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - aiohttp
    - psutil
    - ts-salobj
    - ts-idl
