{% set data= load_setup_py_data() %}
package:
  name: ts-salkafka
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - aiohttp
    - psutil
    - ts-salobj
    - ts-idl
