{% set data= load_setup_py_data() %}
package:
  name: ts-salkafka
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_salkafka_producer = lsst.ts.salkafka:run_salkafka_producer

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm {{ setuptools_scm }}
    - setuptools {{ setuptools }}
  run:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - setuptools_scm {{ setuptools_scm }}
    - aiohttp
    - psutil
    - ts-salobj
    - ts-idl
