{% set data= load_setup_py_data() %}
package:
  name: ts-salkafka
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_salkafka_producer = lsst.ts.salkafka:run_salkafka_producer

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - aiohttp
    - psutil
    - ts-salobj
    - ts-idl

test:
  requires:
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-hexrotcomm
    - ts-simactuators
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - py.test
